Repository uncovertruth/styleguide, pull requests merged in 2018-02, with the labels that each got.

#2 Initial commit
  .gitignore
  .travis.yml
  README.md
  lerna.json
  package.json
  packages/eslint-config-flowtype/.eslintrc.js
  packages/eslint-config-flowtype/.flowconfig
  packages/eslint-config-flowtype/LICENSE
  packages/eslint-config-flowtype/README.md
  packages/eslint-config-flowtype/index.js
  packages/eslint-config-flowtype/package.json
  packages/eslint-config-react/.eslintrc.js
  packages/eslint-config-react/LICENSE
  packages/eslint-config-react/README.md
  packages/eslint-config-react/index.js
  packages/eslint-config-react/package.json
  packages/eslint-config-react/test/index.jsx
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/.yarnclean
  packages/eslint-config/LICENSE
  packages/eslint-config/README.md
  packages/eslint-config/examples/index.js
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  yarn.lock
Labels: in progress

#3 feat(pacakges) Added textlint configs
  .gitignore
  README.md
  package.json
  packages/textlint-config-en/LICENSE
  packages/textlint-config-en/README.md
  packages/textlint-config-en/example/failed.md
  packages/textlint-config-en/index.js
  packages/textlint-config-en/package.json
  packages/textlint-config-ja/LICENSE
  packages/textlint-config-ja/README.md
  packages/textlint-config-ja/example/failed.md
  packages/textlint-config-ja/index.js
  packages/textlint-config-ja/package.json
  yarn.lock
Labels: QA

#5 Added linter
  README.md
  package.json
  packages/markdownlint-config/.markdownlintrc
  packages/markdownlint-config/LICENSE
  packages/markdownlint-config/README.md
  packages/markdownlint-config/example.md
  packages/markdownlint-config/package.json
  packages/pug-lint-config-uncovertruth/.pug-lintrc.json
  packages/pug-lint-config-uncovertruth/LICENSE
  packages/pug-lint-config-uncovertruth/README.md
  packages/pug-lint-config-uncovertruth/package.json
  packages/pug-lint-config-uncovertruth/test/index.pug
  yarn.lock
Labels: in progress

#4 merge tslint-config from master
  README.md
  packages/tslint-config/LICENSE
  packages/tslint-config/README.md
  packages/tslint-config/package.json
  packages/tslint-config/test/index.ts
  packages/tslint-config/tslint.json
  yarn.lock
Labels: in progress

#15 feat(packages) Added stylelint-config
  .travis.yml
  README.md
  packages/stylelint-config/.stylelintrc.js
  packages/stylelint-config/LICENSE
  packages/stylelint-config/README.md
  packages/stylelint-config/index.js
  packages/stylelint-config/package.json
  packages/stylelint-config/test/index.css
  yarn.lock
Labels: QA

#19 fix(packages/stylelint-config) remove peerDependency
  packages/stylelint-config/package.json
Labels: bug, in progress

#23 Relesase v4.0.0-beta1
  lerna.json
  packages/eslint-config-flowtype/package.json
  packages/eslint-config-react/package.json
  packages/eslint-config/package.json
  packages/markdownlint-config/package.json
  packages/pug-lint-config-uncovertruth/package.json
  packages/stylelint-config/package.json
  packages/textlint-config-en/package.json
  packages/textlint-config-ja/package.json
  packages/tslint-config/package.json
Labels: in progress

#28 Release v4.0.0-beta2
  .travis.yml
  lerna.json
  package.json
  packages/eslint-config-flowtype/package.json
  packages/eslint-config-react/package.json
  packages/eslint-config/package.json
  packages/markdownlint-config/package.json
  packages/pug-lint-config-uncovertruth/package.json
  packages/stylelint-config/package.json
  packages/textlint-config-en/package.json
  packages/textlint-config-ja/package.json
  packages/tslint-config/package.json
Labels: in progress

#29 fix(travis) Added repo
  .travis.yml
Labels: QA

#30 fix(travis) remove undefined task
  .travis.yml
Labels: in progress

#31 fix(travis) remove matrix
  .travis.yml
Labels: QA, bug

#32 fix(package) Added can-npm-publish
  package.json
  yarn.lock
Labels: in progress

#33 fix(package) fix publish task
  package.json
Labels: QA, bug

#34 fix(travis) fix npmrc path
  .travis.yml
Labels: in progress

#36 chore(packages) Release v4.0.0
  lerna.json
  packages/eslint-config-flowtype/package.json
  packages/eslint-config-react/package.json
  packages/eslint-config/package.json
  packages/markdownlint-config/package.json
  packages/pug-lint-config-uncovertruth/package.json
  packages/stylelint-config/package.json
  packages/textlint-config-en/package.json
  packages/textlint-config-ja/package.json
  packages/tslint-config/package.json
Labels: QA
