Repository uncovertruth/styleguide, pull requests merged in 2018-07, with the labels that each got.

#143 Release/v4.5.0
  lerna.json
  packages/eslint-config-flowtype/package.json
  packages/eslint-config/package.json
  packages/markdownlint-config/package.json
  packages/tslint-config/package.json
  yarn.lock
Labels: QA

#144 Replace npm token
  .travis.yml
Labels: in progress

#146 Fix remove unnecessary option
  packages/tslint-config/package.json
Labels: in progress

#147 Fix wrong syntax
  .travis.yml
Labels: bug, in progress

#148 Replace token
  .travis.yml
Labels: in progress
